[env]
ARCH = { value = "x86_64", condition = { env_not_set = ["ARCH"] } }
BUILD_DIR = { value = "./build", condition = { env_not_set = ["BUILD_DIR"] } }

[tasks.clean]
command = "rm"
args = ["-rf", "${BUILD_DIR}"]

[tasks.boot]
script = [
'''
mkdir -p ${BUILD_DIR}/boot
nasm -f elf64 kernel/arch/${ARCH}/boot/multiboot_header.asm -o ${BUILD_DIR}/boot/multiboot_header.o
nasm -f elf64 kernel/arch/${ARCH}/boot/boot.asm -o ${BUILD_DIR}/boot/boot.o
'''
]

[tasks.kernel]
dependencies = ["boot"]
script = [
'''
ld --nmagic -T kernel/arch/${ARCH}/poseidon.ld ${BUILD_DIR}/boot/*.o -o ${BUILD_DIR}/poseidon
'''
]

[tasks.iso]
dependencies = ["kernel"]
command = "bash"
args = ["./scripts/gen-iso.sh", "-o", "${BUILD_DIR}/poseidon.iso", "${BUILD_DIR}/poseidon"]

[tasks.qemu]
dependencies = ["iso"]
command = "qemu-system-${ARCH}"
args = ["-cdrom", "${BUILD_DIR}/poseidon.iso"]
